name: shopping_cart
description: A new Flutter shopping cart application.

version: 1.0.4+5

environment:
  sdk: '>=3.0.0 <4.0.0'  # Updated to latest compatible Dart version

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_rating_bar: ^4.0.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.15.1
  flutter_typeahead: ^5.2.0
  dio: ^5.4.0
  get: ^4.6.6
  get_storage: ^2.1.1
  provider: ^6.1.2
  path_provider: ^2.1.2
  email_validator: ^2.1.17
  bottom_navy_bar: ^6.0.0
  fluttertoast: ^8.2.4
  pin_code_text_field: ^1.8.0
  cached_network_image: ^3.3.1
  url_launcher: ^6.2.4
  intl: ^0.19.0
  carousel_slider: ^4.2.1
  carousel_indicator: ^1.0.6
  flutter_windowmanager: ^0.2.0
 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/products/
    - images/settings/
    - images/support/
    - images/wishlist/

  fonts:
    - family: Helvetica
      fonts:
        - asset: fonts/helvetica/HelveticaNeue_Light.ttf
          weight: 200
        - asset: fonts/helvetica/HelveticaNeue_Regular.ttf
          weight: 400
        - asset: fonts/helvetica/HelveticaNeue_Medium.ttf
          weight: 500
        - asset: fonts/helvetica/HelveticaNeue-Bold.ttf
          weight: 700
        - asset: fonts/helvetica/HelveticaNeue_BlackCond.ttf
          weight: 900
    - family: LatoBlack
      fonts:
        - asset: fonts/Lato/lato_black.ttf
    - family: LatoBold
      fonts:
        - asset: fonts/Lato/lato_bold.ttf
    - family: LatoLight
      fonts:
        - asset: fonts/Lato/lato_light.ttf
    - family: LatoMed
      fonts:
        - asset: fonts/Lato/lato_medium.ttf
    - family: LatoReg
      fonts:
        - asset: fonts/Lato/lato_regular.ttf
    - family: LatoSmBold
      fonts:
        - asset: fonts/Lato/lato_semibold.ttf
